version: '3.6'
services:
  app:
    network_mode: "bridge"
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    # command: ["gunicorn", "busy_beaver:app", "-b", "0.0.0.0:5100", "--reload", "--timeout",  "100000"]
    command: ["/bin/bash"]
    env_file: .env
    environment:
      PYTHONPATH: .
      FLASK_APP: /app/busy_beaver/__init__.py
      FLASK_ENV: development
      DATABASE_URI: postgresql://root:1234@172.17.0.2:5432/busy_beaver
    stdin_open: true
    tty: true
    volumes:
      - .:/app/
      - ./logs:/app/logs/
    ports:
      - 8000
